server:
  strategy: Loss-Based-Clustering
  fraction_fit: 1.0
  fraction_eval: 1.0
  dataset_size: 1.0
  num_rounds: 10
  batch_size: 64
client:
  num_clients: 10
  batch_size: 64
  local_epochs: 5
model:
  name: CIFAR10
  learning_rate: 0.001
general:
  use_wandb: false
  random_seed: 42
backend:
  client_resources:
    num_cpus: 2.0
    num_gpus: 0.0
